# -*- coding: utf-8 -*-
"""Welcome to Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

!git clone https://github.com/google-research/vision_transformer.git

# Commented out IPython magic to ensure Python compatibility.
# %cd vision_transformer

!pip install flax jax jaxlib tensorflow gradio pillow matplotlib

!ls

import gradio as gr
from PIL import Image
import torch
from transformers import ViTImageProcessor, ViTForImageClassification

# Load pretrained Vision Transformer model
model_name = "google/vit-base-patch16-224"

processor = ViTImageProcessor.from_pretrained(model_name)
model = ViTForImageClassification.from_pretrained(model_name)

def predict(image):
    # Process image
    inputs = processor(images=image, return_tensors="pt")

    # Model prediction
    with torch.no_grad():
        outputs = model(**inputs)

    logits = outputs.logits

    # Get predicted class
    predicted_class_idx = logits.argmax(-1).item()

    predicted_class = model.config.id2label[predicted_class_idx]

    # Confidence score
    probabilities = torch.nn.functional.softmax(logits, dim=-1)
    confidence = probabilities[0][predicted_class_idx].item()

    return f"Prediction: {predicted_class}\nConfidence: {confidence:.2%}"

# Gradio UI
demo = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="pil"),
    outputs="text",
    title="Vision Transformer Image Classifier",
    description="Upload any image and AI will classify it",
    theme="soft"
)

demo.launch()

